static_resources:
  listeners:
    - name: LB1_OPA_Processed
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 8002 
      filter_chains:
        - filters:                
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: LB1_OPA_Processed
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog                
                route_config:
                  name: remote_route
                  virtual_hosts:
                    - name: ONL
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/org/video/"
                            headers: 
                            - name: "x-secure"
                              exact_match: "user" 
                          route:
                            timeout: 0s
                            idle_timeout: 0s
                            max_stream_duration:
                              max_stream_duration: 0s

                            cluster: video
                            prefix_rewrite: "/"
                        - match:
                            prefix: "/org/video/"
                            headers: 
                            - name: "x-secure"
                              exact_match: "admin" 
                          route:
                            timeout: 0s
                            idle_timeout: 0s
                            max_stream_duration:
                              max_stream_duration: 0s

                            cluster: video
                            prefix_rewrite: "/"
                http_filters:
                  - name: envoy.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router


    - name: LB1_HTTP
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 10000
      filter_chains:
        - filters:
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: LB1_HTTP
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog                
                route_config:              
                  name: remote_route
                  virtual_hosts:
                    - name: connect
                      domains: ["*"]
                      routes:                            
                        - match:
                            prefix: "/org/"                          
                          route:
                            timeout: 0s
                            idle_timeout: 0s
                            max_stream_duration:
                              max_stream_duration: 0s
                            cluster: postOPA
                              
                http2_protocol_options:
                  allow_connect: true
                http_filters:
                  - name: envoy.filters.http.ext_authz
                    typed_config:
                      '@type': type.googleapis.com/envoy.extensions.filters.http.ext_authz.v3.ExtAuthz
                      transport_api_version: V3
                      stat_prefix: ext_authz
                      grpc_service:
                        envoy_grpc:
                          cluster_name: opa
                  - name: envoy.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http2_protocol_options:
                  allow_connect: true
                upgrade_configs:
                - upgrade_type: CONNECT                      

  
  
    - name: LB1_Video
      address:
        socket_address:
          protocol: TCP
          address: 0.0.0.0
          port_value: 7000 
      filter_chains:
        - filters:                
            - name: envoy.filters.network.http_connection_manager
              typed_config:
                "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
                stat_prefix: LB1_Video
                access_log:
                - name: envoy.access_loggers.stdout
                  typed_config:
                    "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog                
                route_config:              
                  name: remote_route
                  virtual_hosts:
                    - name: ONL
                      domains: ["*"]
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            timeout: 0s
                            idle_timeout: 0s
                            max_stream_duration:
                              max_stream_duration: 0s
                            cluster: service_udp
                        - match:
                            connect_matcher: {}
                          route:
                            timeout: 0s
                            idle_timeout: 0s
                            max_stream_duration:
                              max_stream_duration: 0s
                            cluster: service_udp
                            
                http_filters:
                  - name: envoy.router
                    typed_config:
                      "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router
                http2_protocol_options:
                  allow_connect: true
                upgrade_configs:
                - upgrade_type: CONNECT-UDP

  clusters:
                
  - name: opa
    type: LOGICAL_DNS
    lb_policy: ROUND_ROBIN
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: opa
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: host.docker.internal
                port_value: 9191


  - name: postOPA
    connect_timeout: 5s
    type: STATIC
    dns_lookup_family: "V4_ONLY"
    load_assignment:
      cluster_name: postOPA
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 127.0.0.1
                port_value: 8002                 
                
                                                          
  - name: video
    connect_timeout: 5s
    type: STATIC
    dns_lookup_family: "V4_ONLY"
    load_assignment:
      cluster_name: video
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.9.2
                port_value: 10000 

  - name: service_udp
    connect_timeout: 5s
    type: STATIC
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}    
    dns_lookup_family: "V4_ONLY"
    load_assignment:
      cluster_name: service_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.7.1
                port_value: 7000                 


                
