static_resources:
  listeners:

  - name: server1_http
    address:
      socket_address:
        protocol: TCP
        address: 0.0.0.0
        port_value: 10000 
    filter_chains:
      - filters:                
          - name: envoy.filters.network.http_connection_manager
            typed_config:
              "@type": type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
              stat_prefix: server1_http
              access_log:
              - name: envoy.access_loggers.stdout
                typed_config:
                  "@type": type.googleapis.com/envoy.extensions.access_loggers.stream.v3.StdoutAccessLog                
              route_config:              
                name: remote_route
                virtual_hosts:
                  - name: ONL
                    domains: ["*"]
                    routes:
                      - match:                       
                          prefix: "/"
                        route:
                          timeout: 0s
                          idle_timeout: 0s
                          max_stream_duration:
                            max_stream_duration: 0s
                          cluster: video                            
              http_filters:
               - name: envoy.router
                 typed_config:
                   "@type": type.googleapis.com/envoy.extensions.filters.http.router.v3.Router  
              http2_protocol_options:
                allow_connect: true

  - name: server1_udp_http
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 7000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: server1_udp_http
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: service_udp
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          proxy_host: proxy.host.com
          target_host: target.host.com
          default_target_port: 7000
          retry_options:
            max_connect_attempts: 3
          buffer_options:
            max_buffered_datagrams: 10240
            max_buffered_bytes: 163840
          headers_to_add:
          - header:
              key: service
              value: "videoServer1"

  clusters:
  - name: video
    connect_timeout: 5s
    type: LOGICAL_DNS
    dns_lookup_family: "V4_ONLY"
    load_assignment:
      cluster_name: video
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.9.2
                port_value: 8888
  - name: service_udp
    connect_timeout: 5s
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: service_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 192.168.9.1
                port_value: 7000
          
