static_resources:
  listeners:
  - name: listener_0
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10000
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: foo
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: cluster_http
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          proxy_host: user2
          target_host: server1
          retry_options:
            max_connect_attempts: 2
          default_target_port: 443
          buffer_options:
            max_buffered_datagrams: 1024
            max_buffered_bytes: 16384
          headers_to_add:
          - header:
              key: user
              value: "user2"
          - header:
              key: IPaddress
              value: "10.0.0.1"
              
  - name: listener_1
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10001
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: foo
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: cluster_http
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          proxy_host: user2
          target_host: server2
          retry_options:
            max_connect_attempts: 2
          default_target_port: 443
          buffer_options:
            max_buffered_datagrams: 1024
            max_buffered_bytes: 16384
          headers_to_add:           
          - header:
              key: user
              value: "user2"
          - header:
              key: IPaddress
              value: "10.0.0.2"            

  - name: listener_2
    address:
      socket_address:
        protocol: UDP
        address: 0.0.0.0
        port_value: 10002
    listener_filters:
    - name: envoy.filters.udp_listener.udp_proxy
      typed_config:
        '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.UdpProxyConfig
        stat_prefix: foo
        matcher:
          on_no_match:
            action:
              name: route
              typed_config:
                '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.v3.Route
                cluster: cluster_http
        session_filters:
        - name: envoy.filters.udp.session.http_capsule
          typed_config:
            '@type': type.googleapis.com/envoy.extensions.filters.udp.udp_proxy.session.http_capsule.v3.FilterConfig
        tunneling_config:
          proxy_host: user2
          target_host: server3
          retry_options:
            max_connect_attempts: 2
          default_target_port: 443
          buffer_options:
            max_buffered_datagrams: 1024
            max_buffered_bytes: 16384
          headers_to_add:
          - header:
              key: user
              value: "user2"
          - header:
              key: IPaddress
              value: "128.252.0.0"            
            
  clusters:
         
  - name: cluster_http
    connect_timeout: 5s
    common_lb_config: 
      close_connections_on_host_set_change: true
    typed_extension_protocol_options:
      envoy.extensions.upstreams.http.v3.HttpProtocolOptions:
        "@type": type.googleapis.com/envoy.extensions.upstreams.http.v3.HttpProtocolOptions
        explicit_http_config:
          http2_protocol_options: {}
    load_assignment:
      cluster_name: cluster_http
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <Ingress IP Here> 
                port_value: 10000          
                
  - name: cluster_udp
    connect_timeout: 5s
    load_assignment:
      cluster_name: cluster_udp
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: <Ingress IP Here> 
                port_value: 21000                 