version: '3'

services:
  internalhttp:
    image: patrikjuvonen/docker-nginx-http3:2.1.4
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./testFiles/:/usr/share/nginx/html/index/index80/files/:ro
      - ./index/:/usr/share/nginx/html/index/
      
